# MTQuant Hierarchical Multi-Agent System Configuration
# Sprint 3 - Configuration for Meta-Controller, Specialists, and Training

meta_controller:
  state_dim: 74
  hidden_dim: 256
  hidden_dim_2: 128
  dropout: 0.2
  learning_rate: 0.0003

specialists:
  forex:
    type: ForexSpecialist
    instruments: [EURUSD, GBPUSD, USDJPY]
    market_features_dim: 8
    observation_dim: 50  # From environment
    hidden_dim: 64
    learning_rate: 0.0003
  
  commodities:
    type: CommoditiesSpecialist
    instruments: [XAUUSD, WTIUSD]
    market_features_dim: 6
    observation_dim: 50
    hidden_dim: 64
    learning_rate: 0.0003
  
  equity:
    type: EquitySpecialist
    instruments: [SPX500, NAS100, US30]
    market_features_dim: 7
    observation_dim: 50
    hidden_dim: 64
    learning_rate: 0.0003

portfolio_risk:
  max_portfolio_var: 0.02
  max_correlation_exposure: 0.7
  max_sector_allocation: 0.4
  var_confidence: 0.95
  correlation_window: 100

training:
  phase_1_timesteps: 500000  # Individual specialist training
  phase_2_timesteps: 300000  # Meta pre-training
  phase_3_timesteps: 1000000  # Joint fine-tuning
  
  batch_size: 256
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  
  # Multi-agent specific
  meta_update_freq: 1  # Update meta every step
  specialist_update_freq: 5  # Update specialists every 5 steps
  
  # Hardware
  device: "cuda"  # or "cpu"
  n_envs: 8  # Parallel environments

communication:
  message_history_size: 1000
  correlation_id_enabled: true
  log_all_messages: true

monitoring:
  log_interval: 1000  # steps
  save_interval: 10000
  eval_interval: 5000
  eval_episodes: 10