# MTQuant Broker Configuration
# Defines broker-specific settings and mappings

# Demo accounts section (for testing)
demo_accounts:
  ic_markets_mt5:
    broker_id: "ic_markets_mt5_demo"
    platform: "mt5"
    account: 12345678
    password: "${MT5_DEMO_PASSWORD}"  # Reference environment variable
    server: "ICMarkets-Demo"
    description: "IC Markets MT5 Demo Account"
    is_demo: true
    enabled: true
    
  exness_mt5:
    broker_id: "exness_mt5_demo"
    platform: "mt5"
    account: 87654321
    password: "${MT5_DEMO_PASSWORD}"
    server: "Exness-Demo"
    description: "Exness MT5 Demo Account"
    is_demo: true
    enabled: false  # Placeholder for future use
    
  generic_mt4:
    broker_id: "generic_mt4_demo"
    platform: "mt4"
    account: 99999999
    password: "${MT4_DEMO_PASSWORD}"
    server: "Generic-Demo"
    description: "Generic MT4 Demo Account (placeholder)"
    is_demo: true
    enabled: false  # Placeholder for future MT4 support

# Live accounts section (placeholders, will be populated later)
live_accounts:
  ic_markets_mt5_live:
    broker_id: "ic_markets_mt5_live"
    platform: "mt5"
    account: 98765432
    password: "${MT5_LIVE_PASSWORD}"
    server: "ICMarkets-Live"
    description: "IC Markets MT5 Live Account"
    is_demo: false
    enabled: false  # Will be enabled when ready for live trading
    risk_level: "high"
    
  exness_mt5_live:
    broker_id: "exness_mt5_live"
    platform: "mt5"
    account: 11111111
    password: "${MT5_LIVE_PASSWORD}"
    server: "Exness-Live"
    description: "Exness MT5 Live Account"
    is_demo: false
    enabled: false
    risk_level: "high"

# Default broker selection
default_broker: "ic_markets_mt5_demo"

# Broker failover configuration
failover:
  enabled: true
  primary: "ic_markets_mt5_demo"
  secondary: "exness_mt5_demo"
  tertiary: "generic_mt4_demo"
  
  # Failover triggers
  triggers:
    - connection_timeout
    - order_rejection
    - position_sync_failure
    - market_data_stale

# Broker-specific settings
broker_settings:
  mt5:
    # MT5-specific settings
    terminal_path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"
    data_path: "C:\\Users\\%USERNAME%\\AppData\\Roaming\\MetaQuotes\\Terminal\\"
    max_symbols: 1000
    max_history_bars: 10000
    timeout: 5.0
    retry_attempts: 3
    retry_delay: 1.0
    connection_pool_size: 5
    max_orders_per_minute: 60
    max_positions: 100
    
  mt4:
    # MT4-specific settings
    terminal_path: "C:\\Program Files\\MetaTrader 4\\terminal.exe"
    data_path: "C:\\Users\\%USERNAME%\\AppData\\Roaming\\MetaQuotes\\Terminal\\"
    max_symbols: 500
    max_history_bars: 5000
    timeout: 5.0
    retry_attempts: 3
    retry_delay: 1.0
    connection_pool_size: 3
    max_orders_per_minute: 30
    max_positions: 50
