# Risk Management Configuration for MTQuant

# Pre-trade validation limits
price_bands:
  XAUUSD: 0.05    # 5% price band for gold
  EURUSD: 0.02    # 2% price band for major forex
  GBPUSD: 0.02
  USDJPY: 0.02
  WTIUSD: 0.05
  SPX500: 0.03    # 3% price band for indices
  NAS100: 0.03
  US30: 0.03
  default: 0.05   # Default 5% for other instruments

# Position sizing limits
max_position_pct: 0.05        # Max 5% of portfolio per position
max_portfolio_exposure: 1.2   # Max 120% portfolio exposure

# Position sizing methods configuration
position_sizing:
  kelly:
    default_win_rate: 0.55
    default_avg_win: 100
    default_avg_loss: 80
    fraction: 0.25            # Use 25% of Kelly fraction for safety
  
  volatility:
    risk_per_trade: 0.02      # 2% risk per trade
    atr_multiplier: 2.0       # ATR multiplier for stop loss
    max_position_pct: 0.05    # Max 5% position size
  
  fixed:
    fraction: 0.02            # 2% of portfolio per trade
    max_position_pct: 0.05    # Max 5% position size

# Circuit breaker thresholds
circuit_breaker:
  level_1_threshold: -0.05    # -5% daily loss
  level_2_threshold: -0.10    # -10% daily loss
  level_3_threshold: -0.15    # -15% daily loss
  
  # Cooldown periods (minutes)
  level_1_cooldown: 30
  level_2_cooldown: 60
  level_3_cooldown: 120

# Regulatory limits
regulatory:
  max_leverage: 30            # Maximum leverage allowed
  trading_hours:
    forex: "24/5"            # Forex trading hours
    indices: "24/5"          # Indices trading hours (CFDs vary)

# Symbol-specific limits
symbol_limits:
  XAUUSD:
    max_quantity: 1000       # Max 1000 lots
    min_quantity: 0.01       # Min 0.01 lots
    margin_requirement: 0.01 # 1% margin requirement
  
  EURUSD:
    max_quantity: 10000
    min_quantity: 0.01
    margin_requirement: 0.02

  GBPUSD:
    max_quantity: 10000
    min_quantity: 0.01
    margin_requirement: 0.02

  USDJPY:
    max_quantity: 10000
    min_quantity: 0.01
    margin_requirement: 0.02

  WTIUSD:
    max_quantity: 5000
    min_quantity: 0.01
    margin_requirement: 0.02

  SPX500:
    max_quantity: 500
    min_quantity: 0.01
    margin_requirement: 0.05

  NAS100:
    max_quantity: 500
    min_quantity: 0.01
    margin_requirement: 0.05

  US30:
    max_quantity: 500
    min_quantity: 0.01
    margin_requirement: 0.05

# Correlation matrix for risk checks
correlation_matrix:
  # Forex pairs
  EURUSD_GBPUSD: 0.85
  EURUSD_USDJPY: -0.3
  GBPUSD_USDJPY: -0.2
  
  # Gold correlations
  XAUUSD_EURUSD: -0.7
  XAUUSD_USDJPY: -0.3
  XAUUSD_SPX500: -0.4

  # Indices correlations
  SPX500_NAS100: 0.9
  SPX500_US30: 0.8
  NAS100_US30: 0.75

# Risk monitoring
monitoring:
  pre_trade_timeout: 0.05    # 50ms timeout for pre-trade checks
  health_check_interval: 30  # 30 seconds
  alert_thresholds:
    position_size_warning: 0.03  # 3% warning threshold
    exposure_warning: 1.0        # 100% exposure warning
    daily_loss_warning: -0.02    # -2% daily loss warning

# Emergency procedures
emergency:
  max_daily_loss: -0.20      # -20% maximum daily loss
  max_drawdown: -0.30        # -30% maximum drawdown
  emergency_stop: true       # Enable emergency stop functionality
  notification_channels:
    - email
    - discord
    - sms