# MTQuant Symbol Configuration
# Defines trading instruments and their characteristics following SymbolMapper pattern

# Each standard symbol contains metadata and broker-specific mappings
XAUUSD:
  instrument_type: "commodity"
  pip_value: 0.01
  typical_spread: 0.30
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "XAUUSD"
    oanda: "GOLD.pro"
    exness: "XAUUSDm"
    pepperstone: "XAUUSD"

BTCUSD:
  instrument_type: "crypto"
  pip_value: 0.01
  typical_spread: 5.0
  trading_hours: "24/7"
  broker_mappings:
    ic_markets: "BTCUSD"
    oanda: "BTC_USD"
    exness: "BTCUSDm"
    pepperstone: "BTCUSD"

USDJPY:
  instrument_type: "forex"
  pip_value: 0.01
  typical_spread: 0.1
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "USDJPY"
    oanda: "USD_JPY"
    exness: "USDJPYm"
    pepperstone: "USDJPY"

EURUSD:
  instrument_type: "forex"
  pip_value: 0.0001
  typical_spread: 0.1
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "EURUSD"
    oanda: "EUR_USD"
    exness: "EURUSDm"
    pepperstone: "EURUSD"

GBPUSD:
  instrument_type: "forex"
  pip_value: 0.0001
  typical_spread: 0.15
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "GBPUSD"
    oanda: "GBP_USD"
    exness: "GBPUSDm"
    pepperstone: "GBPUSD"

SPX:
  instrument_type: "index"
  pip_value: 0.1
  typical_spread: 0.5
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "US500"
    oanda: "SPX500_USD"
    exness: "US500m"
    pepperstone: "US500"

ETHUSD:
  instrument_type: "crypto"
  pip_value: 0.01
  typical_spread: 3.0
  trading_hours: "24/7"
  broker_mappings:
    ic_markets: "ETHUSD"
    oanda: "ETH_USD"
    exness: "ETHUSDm"
    pepperstone: "ETHUSD"

WTI:
  instrument_type: "commodity"
  pip_value: 0.01
  typical_spread: 0.05
  trading_hours: "24/5"
  broker_mappings:
    ic_markets: "USOIL"
    oanda: "OIL_USD"
    exness: "USOILm"
    pepperstone: "USOIL"